title: "fullcommit"
description: "Python studies, projects, and pro tips"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site URL and timezone
url: "https://junec7020.github.io"
timezone: "Europe/London"

# Show posts dated in the future (helps with UTC differences)
future: true

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# If this is a project site (not username.github.io), set baseurl to the repo name
# Update this if your GitHub repo name differs
baseurl: "/fullcommit"

# Optional: your name or handle
author:
  name: ""

# Navigation
header_pages:
  - about.md

# Excerpts on home
show_excerpts: true


